### ISSUE TITLE
IF function breaks parser

### ISSUE THREAD

**Issue by osaton** [nene/sql-parser-cst#10] opened 2022-12-17 14:48 UTC
```
Syntax Error: Unexpected "IF"
    Was expecting to see: "!", "$", "(", "*", "-", ":", "?", "@", "ALL", "AS", "CASE", "CAST", "CURRENT_DATE", "CURRENT_DATETIME", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "DATE", "DATETIME", "DISTINCT", "EXISTS", "FALSE", "LOCALTIME", "LOCALTIMESTAMP", "NOT", "NULL", "RAISE", "SAFE_CAST", "TIME", "TIMESTAMP", "TRUE", "X", "~", identifier, number, or string
    --> undefined:1:8
      |
    1 | SELECT IF(1, 2, 3)
      |        ^
```

Probably because `IF` is also used for statements, but I don't know enough about peg.js to offer a solution.

**Comment by nene** [comment] 2022-12-17 18:23
The problem is that `IF` is also one of the reserved keywords (in BigQuery and MySQL).

Should check through all the reserved keywords and all the functions and see if there are more overlaps...

**Comment by nene** [comment] 2022-12-17 18:24
The IF function problem should be fixed now though.

**Closed** 2022-12-17 18:24 UTC

**Comment by nene** [comment] 2022-12-17 18:28
Well.. IF is also reserved word in SQLite... but there shouldn't be an `IF` function in SQLite, as there is instead an `IIF` function.

**Comment by nene** [comment] 2022-12-17 18:29
Released 0.9.4 with the fix.
